- name: Configure Static IP on Ubuntu
  hosts: target_server
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install essential tools
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - vim
          - net-tools
          - htop
        state: present
        update_cache: yes

    - name: Backup existing Netplan configuration
      ansible.builtin.copy:
        src: /etc/netplan/50-cloud-init.yaml
        dest: /etc/netplan/50-cloud-init.yaml.bak
        remote_src: yes

    - name: Configure static IP in Netplan
      ansible.builtin.template:
        src: netplan_static.yaml.j2
        dest: /etc/netplan/50-cloud-init.yaml
        mode: '0644'

    - name: Apply Netplan configuration
      ansible.builtin.command: netplan apply
      changed_when: true
